export function logErr(e: object): boolean;
export function throwErr(e: object): never;
export function logWarn(msg: string | object): boolean;
export function logMsg(msg: string | object): string | object;
export function getType(o: object): string;
export function isString(o: object): boolean;
export function isObjectNotEmpty(o: object): boolean;
export function sleep(msec?: number, doReject?: boolean): Promise<any> | null;
export function escapeMatchingChars(str: string, re: RegExp): string | null;
export function stripMatchingChars(str: string, re: RegExp): string | null;
export function convertNumCharRef(str: string, re: RegExp): string | null;
export function convertHtmlChar(str: string): string | null;
export function convertLaTeXChar(str: string): string | null;
export function encodeUrlPart(part: string): string;
export function encodeUrlSpecialChar(str: string): string | undefined;
