export const userOpts: Map<any, any>;
export function setUserOpts(opt?: object): Promise<object>;
export function setUserEnabledFormats(opt?: object): Promise<object>;
export function getFormatTemplate(id: string): string | null;
export function getAllTabsInfo(menuItemId: string): Promise<any[]>;
export function getOtherTabsInfo(menuItemId: string): Promise<any[]>;
export function getSelectedTabsInfo(menuItemId: string): Promise<any[]>;
export function getContextInfo(tabId?: number): Promise<object>;
export function sendContextInfo(): Promise<any>;
export function extractClickedData(info?: object, tab?: object): Promise<any>;
export function handleActiveTab(info?: object): Promise<any>;
export function handleUpdatedTab(tabId: number, info?: object, tab?: object): Promise<any>;
export function handleCmd(cmd: string, tab: object): Promise<any>;
export function handleMsg(msg?: object): Promise<any[]>;
export function setStorageValue(item: string, obj?: object, changed?: boolean): Promise<any>;
export function handleStorage(data: object, area?: string, changed?: boolean): Promise<any[]>;
export function startup(): Promise<any>;
export { enabledFormats };
import { enabledFormats } from './format.js';
